#ifndef GLOBAL_H
#define GLOBAL_H

#define SAMPLE_RATE 16000
#define AUDIO_SLICES 4
#define MICROPHONE_DC_OFFSET 3430
#define MICROPHONE_GAIN 5.6234f

#define DATABUFFER_SAMPLE_COUNT ((SAMPLE_RATE * 3) / 2)
#define MICROPHONE_SAMPLE_COUNT (SAMPLE_RATE / AUDIO_SLICES)
#define INFERENCE_SAMPLE_COUNT (SAMPLE_RATE * 1)
#define SPEAKER_SAMPLE_COUNT (SAMPLE_RATE * 5)

#endif