#ifndef GLOBAL_H
#define GLOBAL_H

#define SAMPLE_RATE 16000
#define MICROPHONE_SAMPLE_COUNT (SAMPLE_RATE)
#define INFERENCE_SAMPLE_COUNT (SAMPLE_RATE * 1)
#define SPEAKER_SAMPLE_COUNT (SAMPLE_RATE * 5)

#endif